# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate covariances between times using a PTide fit
#'
#' Calculate the covariances between times using a PTide fit.
#'
#' @param x A vector of times
#' @param x1 The first vector of times for \code{ptide_cross_covariance}
#' @param x2 A second vector of times for \code{ptide_cross_covariance}
#' @param fit A PTide fit created using \code{\link{ptide_fit}}
#' @param include_noise A vector of 0s and 1s indicating whether to include
#' the white noise term for each time point.
#' @return
#' For \code{ptide_covariance}, a 4-D array of cross-covariances with
#' dimensions n x n x d x d, where n is the length of \code{x} and d is the
#' number of data dimensions. For \code{ptide_cross_covariance}, a 4-D array
#' of cross-covariances with dimensions n1 x n2 x d x d, where n1 and n2 are
#' the lengths of \code{x1} and \code{x2}.
#' @export
ptide_covariance <- function(x, fit, include_noise) {
    .Call(`_ptide_ptideCovariance`, x, fit, include_noise)
}

#' @describeIn ptide_covariance PTide cross covariance
#' @export
ptide_cross_covariance <- function(x1, x2, fit) {
    .Call(`_ptide_ptideCrossCovariance`, x1, x2, fit)
}

.parent_knn <- function(x, n_parents, leaf_size = 40L) {
    .Call(`_ptide_parent_knn`, x, n_parents, leaf_size)
}

.set_tbb_threads <- function(n_threads) {
    .Call(`_ptide_set_tbb_threads`, n_threads)
}

.get_tbb_threads <- function() {
    .Call(`_ptide_get_tbb_threads`)
}

